import { Deal } from "./types";

export const DEALS: Deal[] = [
  {
    id: "d-2026-051",
    date: "2026-05-27",
    target: "Cloud-провайдер Selectel — миноритарный пакет",
    buyer: "ЗПИФ «Инвест Капитал Технологии»",
    seller: "Действующие акционеры",
    sectorId: "it",
    valueBnRub: 14.8,
    stakePct: 11.0,
    type: "PE",
    status: "Announced",
    description:
      "Закрытый ПИФ выкупает 11% Selectel у действующих акционеров с премией к последней оценке. Сделка предполагает оценку компании в 134 млрд руб.",
    sourceTitle: "Selectel получит нового якорного инвестора",
    sourceUrl: "https://www.kommersant.ru/rubric/4",
    sourceOutlet: "Коммерсантъ",
  },
  {
    id: "d-2026-050",
    date: "2026-05-26",
    target: "Группа «М.Видео-Эльдорадо» (доп. эмиссия)",
    buyer: "Структура Эльбрус Капитал",
    seller: "Открытая подписка",
    sectorId: "retail",
    valueBnRub: 22.5,
    stakePct: 19.7,
    type: "PE",
    status: "Closed",
    description:
      "В рамках допэмиссии PE-фонд Эльбрус Капитал получает блокирующий пакет, финансируя реструктуризацию долговой нагрузки и редизайн сети.",
    sourceTitle: "Эльбрус Капитал закрыл инвестицию в М.Видео",
    sourceUrl: "https://www.vedomosti.ru/business",
    sourceOutlet: "Ведомости",
  },
  {
    id: "d-2026-049",
    date: "2026-05-26",
    target: "Сеть клиник «Медси» (миноритарный пакет)",
    buyer: "РФПИ + консорциум арабских инвесторов",
    seller: "АФК «Система»",
    sectorId: "pharma",
    valueBnRub: 18.2,
    stakePct: 15.0,
    type: "M&A",
    status: "Closed",
    description:
      "РФПИ совместно с пулом ближневосточных институционалов выкупает 15% «Медси» у АФК «Система». Оценка сети — около 121 млрд руб.",
    sourceTitle: "РФПИ инвестирует в крупнейшую частную сеть клиник",
    sourceUrl: "https://www.interfax.ru/business",
    sourceOutlet: "Интерфакс",
  },
  {
    id: "d-2026-048",
    date: "2026-05-25",
    target: "Контейнерный терминал «Восточный»",
    buyer: "Группа «Дело»",
    seller: "Глобал Портс",
    sectorId: "transport",
    valueBnRub: 31.6,
    stakePct: 100.0,
    type: "M&A",
    status: "Pending",
    description:
      "Группа «Дело» консолидирует контейнерные мощности Дальнего Востока, выкупая 100% Восточного терминала у Глобал Портс. Ожидается одобрение ФАС.",
    sourceTitle: "Группа «Дело» расширяется на Дальнем Востоке",
    sourceUrl: "https://www.rbc.ru/business/",
    sourceOutlet: "РБК",
  },
  {
    id: "d-2026-047",
    date: "2026-05-25",
    target: "Промышленный холдинг «Алмаз-Антей-Сервис»",
    buyer: "Ростех",
    seller: "Частные акционеры",
    sectorId: "industrial",
    valueBnRub: null,
    stakePct: 51.0,
    type: "M&A",
    status: "Announced",
    description:
      "Ростех получает контрольный пакет сервисного холдинга, специализирующегося на обслуживании промышленного оборудования. Сумма не раскрывается.",
    sourceTitle: "Ростех консолидирует промышленный сервис",
    sourceUrl: "https://tass.ru/ekonomika",
    sourceOutlet: "ТАСС",
  },
  {
    id: "d-2026-046",
    date: "2026-05-24",
    target: "ИТ-интегратор «Софтлайн Сервис»",
    buyer: "Softline (МКПАО «Софтлайн»)",
    seller: "Менеджмент",
    sectorId: "it",
    valueBnRub: 5.4,
    stakePct: 100.0,
    type: "M&A",
    status: "Closed",
    description:
      "Softline консолидирует сервисное подразделение, выкупая 100% у партнёров-менеджеров. Сделка позволит развернуть единую B2B-платформу.",
    sourceTitle: "Softline объединяет сервисные активы",
    sourceUrl: "https://www.cnews.ru/",
    sourceOutlet: "CNews",
  },
  {
    id: "d-2026-045",
    date: "2026-05-23",
    target: "Банк «Точка»",
    buyer: "Т-Банк (бывший Тинькофф)",
    seller: "Группа QIWI / частные акционеры",
    sectorId: "finance",
    valueBnRub: 41.8,
    stakePct: 100.0,
    type: "M&A",
    status: "Pending",
    description:
      "Т-Банк договорился о покупке 100% банка «Точка» — лидера МСБ-сегмента. Сделка требует одобрения ЦБ и ФАС, закрытие — Q3 2026.",
    sourceTitle: "Т-Банк покупает «Точку» у частных акционеров",
    sourceUrl: "https://www.forbes.ru/finansy",
    sourceOutlet: "Forbes Россия",
  },
  {
    id: "d-2026-044",
    date: "2026-05-22",
    target: "Сеть «ВкусВилл» — миноритарный пакет",
    buyer: "Pre-IPO фонд А.Капитал",
    seller: "Институциональные инвесторы",
    sectorId: "retail",
    valueBnRub: 9.7,
    stakePct: 4.5,
    type: "PE",
    status: "Closed",
    description:
      "Pre-IPO фонд приобрёл 4,5% «ВкусВилл» при оценке компании ~215 млрд руб. Деньги направлены на масштабирование dark stores.",
    sourceTitle: "ВкусВилл привлекает раунд перед IPO 2027",
    sourceUrl: "https://www.kommersant.ru/rubric/3",
    sourceOutlet: "Коммерсантъ",
  },
  {
    id: "d-2026-043",
    date: "2026-05-22",
    target: "Газпромнефть-Восток (40%)",
    buyer: "Консорциум китайских инвесторов",
    seller: "Газпромнефть",
    sectorId: "energy",
    valueBnRub: 168.4,
    stakePct: 40.0,
    type: "M&A",
    status: "Announced",
    description:
      "Газпромнефть продаёт 40% дочерней Газпромнефть-Восток китайскому пулу. Сделка обеспечивает долгосрочные контракты на поставки в КНР.",
    sourceTitle: "Газпромнефть-Восток получает китайского партнёра",
    sourceUrl: "https://www.vedomosti.ru/business",
    sourceOutlet: "Ведомости",
  },
  {
    id: "d-2026-042",
    date: "2026-05-21",
    target: "Девелопер «Самолёт» — портфель проектов МО",
    buyer: "ЗПИФ «Дом.РФ Развитие»",
    seller: "ГК Самолёт",
    sectorId: "realestate",
    valueBnRub: 27.3,
    stakePct: null,
    type: "M&A",
    status: "Closed",
    description:
      "Самолёт выводит часть земельного банка в Подмосковье в ЗПИФ под управлением Дом.РФ. Сделка снижает долговую нагрузку и фиксирует прибыль.",
    sourceTitle: "Самолёт расстаётся с частью земельного банка",
    sourceUrl: "https://realty.rbc.ru/",
    sourceOutlet: "РБК Недвижимость",
  },
  {
    id: "d-2026-041",
    date: "2026-05-20",
    target: "Группа «Эконива-АПК»",
    buyer: "Россельхозбанк (структура)",
    seller: "Кредиторы / собственники",
    sectorId: "agro",
    valueBnRub: 78.5,
    stakePct: 67.0,
    type: "Restructuring",
    status: "Closed",
    description:
      "В рамках реструктуризации долга крупнейший молочный производитель переходит под контроль структуры РСХБ. План — финансовое оздоровление в течение 3 лет.",
    sourceTitle: "РСХБ забирает контроль над Эконивой",
    sourceUrl: "https://www.kommersant.ru/rubric/4",
    sourceOutlet: "Коммерсантъ",
  },
  {
    id: "d-2026-040",
    date: "2026-05-19",
    target: "Оператор ЦОД IXcellerate",
    buyer: "МТС Web Services",
    seller: "Hutton Collins Capital Partners",
    sectorId: "telecom",
    valueBnRub: 24.6,
    stakePct: 100.0,
    type: "M&A",
    status: "Pending",
    description:
      "МТС Web Services выкупает 100% IXcellerate, удваивая мощности по сдаче стойко-мест в Московском регионе. Сделка ожидает одобрения регуляторов.",
    sourceTitle: "МТС покупает крупного оператора дата-центров",
    sourceUrl: "https://www.cnews.ru/",
    sourceOutlet: "CNews",
  },
  {
    id: "d-2026-039",
    date: "2026-05-18",
    target: "Производитель дженериков «Фармасинтез»",
    buyer: "ВЭБ.РФ + Минпромторг",
    seller: "Семейство Шакировых (миноритарный пакет)",
    sectorId: "pharma",
    valueBnRub: 12.4,
    stakePct: 17.5,
    type: "PE",
    status: "Closed",
    description:
      "Государственная структура входит в капитал крупного производителя жизненно необходимых препаратов. Инвестиция увязана с программой импортозамещения.",
    sourceTitle: "ВЭБ инвестирует в Фармасинтез",
    sourceUrl: "https://www.interfax.ru/business",
    sourceOutlet: "Интерфакс",
  },
  {
    id: "d-2026-038",
    date: "2026-05-17",
    target: "Кибербезопасность F.A.C.C.T.",
    buyer: "VK / Ростелеком (СП)",
    seller: "Менеджмент + миноритарии",
    sectorId: "it",
    valueBnRub: 8.9,
    stakePct: 100.0,
    type: "M&A",
    status: "Closed",
    description:
      "СП VK и Ростелекома консолидирует одного из ведущих игроков рынка threat intelligence. Цель — создать единый национальный SOC-провайдер.",
    sourceTitle: "VK и Ростелеком купили F.A.C.C.T.",
    sourceUrl: "https://www.cnews.ru/",
    sourceOutlet: "CNews",
  },
  {
    id: "d-2026-037",
    date: "2026-05-16",
    target: "ТГК-2 (контрольный пакет)",
    buyer: "Группа «Газпром энергохолдинг»",
    seller: "Конкурсный управляющий",
    sectorId: "energy",
    valueBnRub: 17.9,
    stakePct: 80.6,
    type: "M&A",
    status: "Closed",
    description:
      "Газпром энергохолдинг выкупает контрольный пакет ТГК-2 в рамках банкротных торгов. Энергетика Северо-Запада консолидируется у госхолдинга.",
    sourceTitle: "Газпром энергохолдинг забирает ТГК-2",
    sourceUrl: "https://www.kommersant.ru/rubric/4",
    sourceOutlet: "Коммерсантъ",
  },
  {
    id: "d-2026-036",
    date: "2026-05-15",
    target: "Производитель упаковки «Готэк»",
    buyer: "PE-фонд «Бэринг Восток-2 (преемник)»",
    seller: "Семейство Чуйковых",
    sectorId: "industrial",
    valueBnRub: 19.8,
    stakePct: 75.0,
    type: "Buyout",
    status: "Announced",
    description:
      "Управленческий buyout с привлечением PE-фонда: команда менеджеров совместно с инвестором выкупает 75% «Готэк» у основателей.",
    sourceTitle: "«Готэк» сменит собственника",
    sourceUrl: "https://www.vedomosti.ru/business",
    sourceOutlet: "Ведомости",
  },
  {
    id: "d-2026-035",
    date: "2026-05-14",
    target: "Логистика «ПЭК» (доп. эмиссия)",
    buyer: "ВТБ Капитал PE",
    seller: "Открытая подписка",
    sectorId: "transport",
    valueBnRub: 11.2,
    stakePct: 24.0,
    type: "PE",
    status: "Closed",
    description:
      "PE-подразделение ВТБ Капитал входит в ПЭК через допэмиссию. Привлечённые средства — на цифровизацию и развитие e-com фулфилмента.",
    sourceTitle: "ВТБ Капитал инвестирует в ПЭК",
    sourceUrl: "https://www.forbes.ru/biznes",
    sourceOutlet: "Forbes Россия",
  },
  {
    id: "d-2026-034",
    date: "2026-05-13",
    target: "X5 Group — доля в JV с Магнит (Маркетплейс «Поиск»)",
    buyer: "Магнит",
    seller: "X5 Group",
    sectorId: "retail",
    valueBnRub: 6.8,
    stakePct: 50.0,
    type: "M&A",
    status: "Closed",
    description:
      "Магнит выкупает долю X5 в совместном маркетплейс-проекте. После сделки актив переходит под единое управление Магнита.",
    sourceTitle: "Магнит консолидирует маркетплейс «Поиск»",
    sourceUrl: "https://www.kommersant.ru/rubric/3",
    sourceOutlet: "Коммерсантъ",
  },
  {
    id: "d-2026-033",
    date: "2026-05-12",
    target: "Платформа онлайн-обучения Skillbox",
    buyer: "VK",
    seller: "Миноритарные акционеры",
    sectorId: "it",
    valueBnRub: 7.3,
    stakePct: 25.1,
    type: "M&A",
    status: "Closed",
    description:
      "VK увеличивает долю в Skillbox до контрольной, выкупая 25,1% у миноритариев. EdTech-направление становится самостоятельным юнитом холдинга.",
    sourceTitle: "VK увеличивает долю в Skillbox до контроля",
    sourceUrl: "https://www.vedomosti.ru/business",
    sourceOutlet: "Ведомости",
  },
  {
    id: "d-2026-032",
    date: "2026-05-11",
    target: "Девелопер «Гранель» — портфель апарт-отелей",
    buyer: "ЗПИФ «Тинькофф Доходная Недвижимость»",
    seller: "ГК Гранель",
    sectorId: "realestate",
    valueBnRub: 14.1,
    stakePct: null,
    type: "M&A",
    status: "Closed",
    description:
      "ЗПИФ под управлением Т-Банка приобретает портфель из трёх апарт-отелей в Москве и Сочи. Сделка — продолжение тренда на секьюритизацию доходной недвижимости.",
    sourceTitle: "Т-Банк нарастил портфель аренды на 14 млрд руб.",
    sourceUrl: "https://realty.rbc.ru/",
    sourceOutlet: "РБК Недвижимость",
  },
];

export function getDealsBySector(sectorId: string, limit?: number): Deal[] {
  const filtered = DEALS.filter((d) => d.sectorId === sectorId).sort(
    (a, b) => +new Date(b.date) - +new Date(a.date),
  );
  return typeof limit === "number" ? filtered.slice(0, limit) : filtered;
}

export function getRecentDeals(limit = 10): Deal[] {
  return [...DEALS]
    .sort((a, b) => +new Date(b.date) - +new Date(a.date))
    .slice(0, limit);
}
