import { Multiplier } from "./types";

export const MULTIPLIERS: Multiplier[] = [
  // IT
  {
    sectorId: "it",
    metric: "EV/EBITDA",
    median: 9.8,
    low: 6.2,
    high: 14.5,
    trend: "up",
    trendPct: 4.2,
    updatedAt: "2026-05-26",
    source: "Аналитика SberCIB Investment Research",
    sourceUrl: "https://www.sberbank.com/ru/analytics",
  },
  {
    sectorId: "it",
    metric: "EV/Sales",
    median: 2.9,
    low: 1.4,
    high: 5.8,
    trend: "up",
    trendPct: 6.1,
    updatedAt: "2026-05-26",
    source: "ВТБ Капитал — Tech Equity Strategy",
    sourceUrl: "https://broker.vtb.ru/analitika/",
  },
  {
    sectorId: "it",
    metric: "P/E",
    median: 17.4,
    low: 11.0,
    high: 28.5,
    trend: "up",
    trendPct: 3.1,
    updatedAt: "2026-05-26",
    source: "Альфа-Капитал Research",
    sourceUrl: "https://www.alfacapital.ru/analytics/",
  },

  // Retail
  {
    sectorId: "retail",
    metric: "EV/EBITDA",
    median: 5.4,
    low: 3.8,
    high: 7.9,
    trend: "down",
    trendPct: -2.3,
    updatedAt: "2026-05-25",
    source: "БКС Мир Инвестиций — Sector Note",
    sourceUrl: "https://bcs-express.ru/analytics",
  },
  {
    sectorId: "retail",
    metric: "P/E",
    median: 9.6,
    low: 6.1,
    high: 14.0,
    trend: "flat",
    trendPct: 0.4,
    updatedAt: "2026-05-25",
    source: "Газпромбанк Инвестиции",
    sourceUrl: "https://gazprombank.investments/",
  },
  {
    sectorId: "retail",
    metric: "EV/Sales",
    median: 0.7,
    low: 0.4,
    high: 1.2,
    trend: "down",
    trendPct: -1.8,
    updatedAt: "2026-05-25",
    source: "ИК Ренессанс Капитал",
    sourceUrl: "https://www.rencap.com/",
  },

  // Finance
  {
    sectorId: "finance",
    metric: "P/B",
    median: 0.84,
    low: 0.45,
    high: 1.35,
    trend: "up",
    trendPct: 5.6,
    updatedAt: "2026-05-27",
    source: "Банк России — Обзор финансовой стабильности",
    sourceUrl: "https://www.cbr.ru/analytics/",
  },
  {
    sectorId: "finance",
    metric: "P/E",
    median: 5.2,
    low: 3.4,
    high: 8.1,
    trend: "up",
    trendPct: 3.9,
    updatedAt: "2026-05-27",
    source: "SberCIB Banking Strategy",
    sourceUrl: "https://www.sberbank.com/ru/analytics",
  },

  // Energy
  {
    sectorId: "energy",
    metric: "EV/EBITDA",
    median: 3.6,
    low: 2.1,
    high: 5.4,
    trend: "down",
    trendPct: -3.5,
    updatedAt: "2026-05-26",
    source: "Газпромбанк — Нефть и газ",
    sourceUrl: "https://gazprombank.investments/",
  },
  {
    sectorId: "energy",
    metric: "P/E",
    median: 4.7,
    low: 2.9,
    high: 7.2,
    trend: "down",
    trendPct: -2.1,
    updatedAt: "2026-05-26",
    source: "БКС Мир Инвестиций",
    sourceUrl: "https://bcs-express.ru/analytics",
  },

  // Real Estate
  {
    sectorId: "realestate",
    metric: "P/B",
    median: 1.12,
    low: 0.65,
    high: 1.85,
    trend: "up",
    trendPct: 2.7,
    updatedAt: "2026-05-24",
    source: "ДОМ.РФ Аналитика",
    sourceUrl: "https://дом.рф/",
  },
  {
    sectorId: "realestate",
    metric: "EV/EBITDA",
    median: 6.1,
    low: 4.2,
    high: 9.3,
    trend: "flat",
    trendPct: 0.8,
    updatedAt: "2026-05-24",
    source: "JLL Россия — Capital Markets",
    sourceUrl: "https://www.jll.ru/",
  },

  // Industrial
  {
    sectorId: "industrial",
    metric: "EV/EBITDA",
    median: 5.8,
    low: 3.7,
    high: 8.9,
    trend: "up",
    trendPct: 4.8,
    updatedAt: "2026-05-26",
    source: "Альфа-Капитал — Промышленный обзор",
    sourceUrl: "https://www.alfacapital.ru/analytics/",
  },
  {
    sectorId: "industrial",
    metric: "P/E",
    median: 7.4,
    low: 4.8,
    high: 11.6,
    trend: "up",
    trendPct: 2.4,
    updatedAt: "2026-05-26",
    source: "ВТБ Капитал — Industrials",
    sourceUrl: "https://broker.vtb.ru/analitika/",
  },

  // Pharma
  {
    sectorId: "pharma",
    metric: "EV/EBITDA",
    median: 8.2,
    low: 5.4,
    high: 12.7,
    trend: "up",
    trendPct: 7.3,
    updatedAt: "2026-05-25",
    source: "DSM Group — Russian Pharma",
    sourceUrl: "https://dsm.ru/",
  },
  {
    sectorId: "pharma",
    metric: "EV/Sales",
    median: 1.9,
    low: 1.1,
    high: 3.4,
    trend: "up",
    trendPct: 5.2,
    updatedAt: "2026-05-25",
    source: "RNC Pharma",
    sourceUrl: "https://rncph.ru/",
  },

  // Telecom
  {
    sectorId: "telecom",
    metric: "EV/EBITDA",
    median: 4.1,
    low: 2.9,
    high: 6.2,
    trend: "flat",
    trendPct: 0.6,
    updatedAt: "2026-05-25",
    source: "TMT Consulting",
    sourceUrl: "https://tmt-consulting.ru/",
  },
  {
    sectorId: "telecom",
    metric: "P/E",
    median: 8.9,
    low: 5.7,
    high: 13.4,
    trend: "flat",
    trendPct: -0.3,
    updatedAt: "2026-05-25",
    source: "ВТБ Капитал — Telecom",
    sourceUrl: "https://broker.vtb.ru/analitika/",
  },

  // Agro
  {
    sectorId: "agro",
    metric: "EV/EBITDA",
    median: 5.2,
    low: 3.4,
    high: 7.6,
    trend: "up",
    trendPct: 3.8,
    updatedAt: "2026-05-24",
    source: "Институт конъюнктуры аграрного рынка (ИКАР)",
    sourceUrl: "https://ikar.ru/",
  },
  {
    sectorId: "agro",
    metric: "P/E",
    median: 6.8,
    low: 4.2,
    high: 10.5,
    trend: "up",
    trendPct: 4.1,
    updatedAt: "2026-05-24",
    source: "Russian Agro Outlook — Газпромбанк",
    sourceUrl: "https://gazprombank.investments/",
  },

  // Transport
  {
    sectorId: "transport",
    metric: "EV/EBITDA",
    median: 4.6,
    low: 3.1,
    high: 7.0,
    trend: "up",
    trendPct: 2.9,
    updatedAt: "2026-05-25",
    source: "INFOLine — Логистика РФ",
    sourceUrl: "https://infoline.spb.ru/",
  },
  {
    sectorId: "transport",
    metric: "P/E",
    median: 7.1,
    low: 4.5,
    high: 11.2,
    trend: "up",
    trendPct: 1.8,
    updatedAt: "2026-05-25",
    source: "БКС — Transport Sector",
    sourceUrl: "https://bcs-express.ru/analytics",
  },
];

export function getMultipliersBySector(sectorId: string): Multiplier[] {
  return MULTIPLIERS.filter((m) => m.sectorId === sectorId);
}
